spring:
    profiles:
        active: dev
    liquibase:
        enabled: true
        change-log: classpath:liquibase/master.xml
    datasource:
        url: jdbc:h2:file:~/.database/expressionDb
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect

server:
    port: 8090